# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a7fb75e7bd74dbbc597c3a0aae26f3dba0f575b4c3c94410819e5ec3c1182ca61fe8032930245e79ea69544bf3d9936db90dc1247c0f2c8bb75e0c41d9de42

test:
  secret_key_base: 245fe0a58aa1f2b63b87f847abb9022ab468702b9454619e2b88b59d2798ac3b2769ba0b84b2947232dd52c2f5abe19b578e7ce9e0a0076390ebe15150a9d002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
